Add the disable_open_sessions_after_failure config option
ni/jupyterhub-winauthenticator pull request #3
Opened 2019-11-04 15:00 UTC by ociule

I dislike the current behaviour that disables open_sessions after a failure.

I have found that after restarting jupyter_hub, users already logged in can't start a server, because of a stale token issue - they get an error 500. Furthermore, this disables open_sessions which means the server now needs restarting.

So I added the disable_open_sessions_after_failure config option, which I set to False in my config.  The users need to logout and login again to bypass the stale token issue.

To be honest, I'd rather remove the behaviour that disables open_sessions - people that do not need it can already disable it by setting open_sessions to False. But if there's a case for keeping it, here's the PR that enables both uses.

2019-11-04 17:29 UTC, adelcast commented
I agree, a better solution would be to just remove the behaviour that disables open_sessions after failure and get rid of this option. That sounds cleaner...

2019-11-05 08:46 UTC, ociule commented
OK, removed the proposed option and the mechanism that disabled open_sessions.

2019-11-05 16:06 UTC, adelcast requested changes
any reason why the same change here was not applied on the exception handler on post_spawn_stop?

2019-11-05 16:53 UTC, ociule commented
> any reason why the same change here was not applied on the exception handler on post_spawn_stop?

Just missed that, done.

2019-11-05 17:07 UTC, adelcast approved these changes
LGTM, thanks !

2019-11-05 17:07 UTC, merged